from __future__ import annotations

from typing import Iterable, Protocol


class EngineAdapter(Protocol):
    def launch(self, run_id: str, skill_id: str, prompt: str, conversation_title: str) -> object: ...
    def iter_raw_events(self, process: object) -> Iterable[dict]: ...
    def cancel(self, process: object) -> None: ...
    def map_event(self, raw_event: dict) -> list[dict]: ...

